
# This is a basic workflow that is manually triggered
env:
  avminfo: '20.124.189.148'
  uusername: 'chabbouhUserName'
  ppassword: 'Marwen@12345'
  
name: Azure Deployment


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest

  # This workflow contains a single job called "greet"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az upgrade
          az version
          
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}      
      

      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.avminfo }}
          username: ${{ env.uusername }}
          password: ${{ env.ppassword }}
          script: |
            echo "Connected to Azure VM"
            
            
        
        
 
          
          


        
  


     
