# This is a basic workflow that is manually triggered

name: Azure Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest


  # This workflow contains a single job called "greet"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      
      - name: Create gr
        run: az deployment sub create --subscription "Microsoft Azure Sponsorship" --location eastus  --template-file ResourceGroup.bicep
    
      - name: Deploy Bicep Template
        run: az deployment group create --resource-group pfeIacRg --template-file Keyvault.bicep
    
      - name: create KeyVault
        id: generate_password
        run: |
          password=$(az rest --method POST --uri 'https://pfeIacKv.vault.azure.net/keys/KEY_NAME/create?api-version=7.2' --header "Authorization: Bearer ${{ secrets.AZURE_TOKEN }}" --body '{"kty": "oct", "key_ops": ["unwrapKey", "wrapKey", "decrypt", "encrypt"], "key_size": 256, "attributes": {"enabled": true}, "key_attributes": {"expires": "2025-12-31T00:00:00+00:00", "notBefore": "2022-01-01T00:00:00+00:00", "created": "2022-01-01T00:00:00+00:00"}}' | jq -r '.value')
          echo "::set-output name=password::$password"


     
