# This is a basic workflow that is manually triggered
env:
  padressPublic: ''
  puserName: ''
  pmotdepasse: ''
  
name: Azure Deployment


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest

  # This workflow contains a single job called "greet"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az upgrade
          az version
          
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}      
      

      - name: Get VM IP address
      
        run: |
          az vm list-ip-addresses --resource-group pfeIacRg1 --name chabbouhTestVm
          avminfo=$(az vm list-ip-addresses --resource-group pfeIacRg1 --name chabbouhTestVm --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress" --output tsv)
          echo "VM IP address: $avminfo"
          username=$(az vm show --resource-group pfeIacRg1 --name chabbouhTestVm --query 'osProfile.adminUsername' --output tsv)
          password=$(az vm show --resource-group pfeIacRg1 --name chabbouhTestVm --query 'osProfile.adminPassword' --output tsv)
          echo "VM username: $username"
          echo "VM password: $password"
          echo "padressPublic=$avminfo" >> $GITHUB_ENV
          echo "puserName=$username" >> $GITHUB_ENV
          echo "pmotdepasse=$password" >> $GITHUB_ENV
 
      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.padressPublic }}
          username: ${{ env.puserName }} 
          password: ${{ env.pmotdepasse }} 
          script: |
            echo "Connected to Azure VM"
            echo "VM username: ${{ env.padressPublic }}"
            echo "VM username: ${{ env.puserName }}"
        
        
        
 
          
          


        
  


     
