
# This is a basic workflow that is manually triggered

name: Azure Deployment


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - main
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    runs-on: ubuntu-latest

  # This workflow contains a single job called "greet"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az upgrade
          az version
          
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}      
      
      - name: Deploy 
        run: az account list --output table
      
      
      - name: Create gr
        run: az deployment sub create --subscription "TMT-NON-PROD-PLATFORM-01" --location eastus --template-file ResourceGroup.bicep
             
     
      - name: Deploy Bicep Template
        run: az deployment group create --resource-group pfeIacRg1 --template-file main.bicep
        
      - name: Get VM IP address
        run: |
          vm_info=$(az vm show --resource-group pfeIacRg1 --name chabbouhTestVm --query publicIps --output tsv)
          echo "VM IP address: $vm_info"
          username=$(az vm show --resource-group pfeIacRg1 --name chabbouhTestVm --query 'osProfile.adminUsername' --output tsv)
          password=$(az vm show --resource-group pfeIacRg1 --name chabbouhTestVm --query 'osProfile.adminPassword' --output tsv)
          echo "VM username: $username"
          echo "VM password: $password"

          
      - name: Open ports on VM
        run: |
          az network nsg rule create --resource-group pfeIacRg1 --nsg-name chabbouhNSG --name SSH --protocol Tcp --direction Inbound --priority 100 --destination-port-ranges 22
          az network nsg rule create --resource-group pfeIacRg1 --nsg-name chabbouhNSG --name HTTP --protocol Tcp --direction Inbound --priority 101 --destination-port-ranges 80
          az network nsg rule create --resource-group pfeIacRg1 --nsg-name chabbouhNSG --name HTTPS --protocol Tcp --direction Inbound --priority 102 --destination-port-ranges 443 
          
      - name: Install SSH client
        run: |
          sudo apt-get install -y openssh-client
          az sshkey create --name mySSHKey --resource-group pfeIacRg1
          private_key_path=$(az sshkey show --name mySSHKey --resource-group pfeIacRg1 --query 'privateKeyFile' --output tsv)
          echo "Private key path: $private_key_path"
          ssh -identity_file /home/runner/.ssh/ username@vm_info
        
  


     
